Beauty Salon/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Beauty_Salon.Models
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Логин")]
        public string UserName { get; set; }

        [Required]
        [UIHint("password")]
        [Display(Name = "Пароль")]
        public string Password { get; set; }

        [Display(Name = "Запомнить меня?")]
        public bool RememberMe { get; set; }
    }
}

Beauty Salon/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Beauty_Salon.Domain;
using Microsoft.AspNetCore.Mvc;

namespace Beauty_Salon.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        private readonly DataManager dataManager;

        public HomeController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index()
        {
            return View(dataManager.ServiceItems.GetServiceItems());
        }
    }
}

Beauty Salon/Areas/Admin/Controllers/ServiceItemsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Beauty_Salon.Domain;
using Beauty_Salon.Domain.Entities;
using Beauty_Salon.Service;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Beauty_Salon.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ServiceItemsController : Controller
    {
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostingEnvironment;
        public ServiceItemsController(DataManager dataManager, IWebHostEnvironment hostingEnvironment)
        {
            this.dataManager = dataManager;
            this.hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Edit(Guid id)
        {
            var entity = id == default ? new ServiceItem() : dataManager.ServiceItems.GetServiceItemById(id);
            return View(entity);
        }
        [HttpPost]
        public IActionResult Edit(ServiceItem model, IFormFile titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    model.TitleImagePath = titleImageFile.FileName;
                    using (var stream = new FileStream(Path.Combine(hostingEnvironment.WebRootPath, "images/", titleImageFile.FileName), FileMode.Create))
                    {
                        titleImageFile.CopyTo(stream);
                    }
                }
                dataManager.ServiceItems.SaveServiceItem(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            dataManager.ServiceItems.DeleteServiceItem(id);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }
    }
}

Beauty Salon/Areas/Admin/Controllers/TextFieldsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Beauty_Salon.Domain;
using Beauty_Salon.Domain.Entities;
using Beauty_Salon.Service;
using Microsoft.AspNetCore.Mvc;

namespace Beauty_Salon.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TextFieldsController : Controller
    {
        private readonly DataManager dataManager;
        public TextFieldsController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Edit(string codeWord)
        {
            var entity = dataManager.TextFields.GetTextFieldByCodeWord(codeWord);
            return View(entity);
        }

        [HttpPost]
        public IActionResult Edit(TextField model)
        {
            if (ModelState.IsValid)
            {
                dataManager.TextFields.SaveTextField(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }
    }
}

Beauty Salon/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Beauty_Salon.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Beauty_Salon.Controllers
{
    [Authorize]
    public class AccountController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;
        public AccountController(UserManager<IdentityUser> userMgr, SignInManager<IdentityUser> signinMgr)
        {
            userManager = userMgr;
            signInManager = signinMgr;
        }

        [AllowAnonymous]
        public IActionResult Login(string returnUrl)
        {
            ViewBag.returnUrl = returnUrl;
            return View(new LoginViewModel());
        }
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginViewModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                IdentityUser user = await userManager.FindByNameAsync(model.UserName);
                if (user != null)
                {
                    await signInManager.SignOutAsync();
                    Microsoft.AspNetCore.Identity.SignInResult result = await signInManager.PasswordSignInAsync(user, model.Password, model.RememberMe, false);
                    if (result.Succeeded)
                    {
                        return Redirect(returnUrl ?? "/");
                    }
                }
                ModelState.AddModelError(nameof(LoginViewModel.UserName), "Неверный логин или пароль");
            }
            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

Beauty Salon/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Beauty_Salon.Domain;
using Microsoft.AspNetCore.Mvc;

namespace Beauty_Salon.Controllers
{
    public class HomeController : Controller
    {
        private readonly DataManager dataManager;

        public HomeController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index()
        {
            return View(dataManager.TextFields.GetTextFieldByCodeWord("PageIndex"));
        }

        public IActionResult Contacts()
        {
            return View(dataManager.TextFields.GetTextFieldByCodeWord("PageContacts"));
        }
    }
}

Beauty Salon/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Beauty_Salon.Domain;
using Microsoft.AspNetCore.Mvc;

namespace Beauty_Salon.Controllers
{
    public class ServicesController : Controller
    {
        private readonly DataManager dataManager;

        public ServicesController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index(Guid id)
        {
            if (id != default)
            {
                return View("Show", dataManager.ServiceItems.GetServiceItemById(id));
            }

            ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeWord("PageServices");
            return View(dataManager.ServiceItems.GetServiceItems());
        }
    }
}

Beauty Salon/Areas/Admin/Views/Home/Index.cshtml
@model IQueryable<ServiceItem>
@{
    string strTitle = "Панель администратора";
    ViewBag.Title = strTitle;
}

<div>
    <h2>@strTitle</h2>
    <div>
        <h3>Наши услуги</h3>
        <div class="div-box">
            <a asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" asp-route-id="">Добавить услугу</a>
        </div>
        @if (Model.Any())
        {
            <div>
                @foreach (ServiceItem entity in Model)
                {
                    <div>
                        <a asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" asp-route-id="@entity.Id">редактировать</a>
                        |
                        <form style="display: inline-block;" id="form-@entity.Id" asp-area="Admin" asp-controller="ServiceItems" asp-action="Delete" method="post">
                            <input type="hidden" name="id" value="@entity.Id">
                            <a href="#" onclick="document.getElementById('form-@entity.Id').submit();">удалить</a>
                        </form>
                        |
                        <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="@entity.Id">
                            @($"{entity.Title}")
                        </a>
                    </div>
                }
            </div>
        }
    </div>
    <div class="div-box">
        <h3>Редактировать страницы сайта</h3>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageIndex">Главная</a>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageServices">Наши услуги</a>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageContacts">Контакты</a>
    </div>
    <div class="div-box">
        <form asp-area="" asp-controller="Account" asp-action="Logout" method="post">
            <input type="submit" value="Выйти" />
        </form>
    </div>
</div>

Beauty Salon/Areas/Admin/Views/ServiceItems/Edit.cshtml
@model ServiceItem
@{
    string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;
}

<script src="~/js/ckeditor/ckeditor.js"></script>

<div>
    <h2>@strTitle</h2>
    <div>
        <form asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DateAdded" />
            <input type="hidden" asp-for="TitleImagePath" />

            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label asp-for="Title"></label>
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>
            <div class="div-box">
                <label asp-for="Subtitle"></label>
                <input asp-for="Subtitle" />
                <span asp-validation-for="Subtitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="Text"></label>
                <textarea asp-for="Text"></textarea>
                <span asp-validation-for="Text"></span>
            </div>
            <div class="div-box">
                <label asp-for="TitleImagePath"></label>
                <input type="file" name="titleImageFile" id="titleImageFile" />
                <div>
                    <img class="img-block" src="~/images/@Model.TitleImagePath" />
                </div>
            </div>
            <div class="div-box">
                <label asp-for="MetaTitle"></label>
                <input asp-for="MetaTitle" />
                <span asp-validation-for="MetaTitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaDescription"></label>
                <input asp-for="MetaDescription" />
                <span asp-validation-for="MetaDescription"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaKeywords"></label>
                <input asp-for="MetaKeywords" />
                <span asp-validation-for="MetaKeywords"></span>
            </div>
            <input type="submit" value="Сохранить" />
        </form>
    </div>
</div>



<script>
    window.onload = function() {
        var newCKEdit = CKEDITOR.replace('@Html.IdFor(x=>x.Text)');
        newCKEdit.updateElement();
    }
</script>

Beauty Salon/Areas/Admin/Views/TextFields/Edit.cshtml
@model TextField
@{
    string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;
}

<script src="~/js/ckeditor/ckeditor.js"></script>

<div>
    <h2>@strTitle</h2>
    <div>
        <form asp-area="Admin" asp-controller="TextFields" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DateAdded" />
            <input type="hidden" asp-for="CodeWord" />

            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label asp-for="Title"></label>
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>
            <div class="div-box">
                <label asp-for="Text"></label>
                <textarea asp-for="Text"></textarea>
                <span asp-validation-for="Text"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaTitle"></label>
                <input asp-for="MetaTitle" />
                <span asp-validation-for="MetaTitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaDescription"></label>
                <input asp-for="MetaDescription" />
                <span asp-validation-for="MetaDescription"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaKeywords"></label>
                <input asp-for="MetaKeywords" />
                <span asp-validation-for="MetaKeywords"></span>
            </div>
            <input type="submit" value="Сохранить" />
        </form>
    </div>
</div>



<script>
    window.onload = function() {
        var newCKEdit = CKEDITOR.replace('@Html.IdFor(x=>x.Text)');
        newCKEdit.updateElement();
    }
</script>

Beauty Salon/Views/Home/Contacts.cshtml
@model TextField
@{
    ViewBag.Title = Model.MetaTitle;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords = Model.MetaKeywords;
}

<div>
    @Html.Raw(Model.Text)
</div>

Beauty Salon/Views/Home/Index.cshtml
<div>
    <h1>Это главная страница</h1>
</div>

Beauty Salon/Views/Services/Index.cshtml
@model IQueryable<ServiceItem>
@{
    TextField textField = ViewBag.TextField;

    ViewBag.Title = textField.MetaTitle;
    ViewBag.Description = textField.MetaDescription;
    ViewBag.Keywords = textField.MetaKeywords;
}

<div>
    @if (Model.Any())
    {
        <ul class="big-image-list">
            @foreach (ServiceItem entity in Model)
            {
                <li>
                    <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="@entity.Id">
                        <img src="~/images/@entity.TitleImagePath" alt="" class="left" />
                    </a>
                    <h4>@entity.Title</h4>
                    <p>@entity.Subtitle</p>
                </li>
            }
        </ul>
    }
</div>

Beauty Salon/Views/Shared/AboutPartial.cshtml
@using Beauty_Salon.Service

<section id="intro" class="wrapper style1 fullscreen fade-up">
    <div class="inner">
        <h1>@Config.CompanyName</h1>
        <h2>Ваша красота - наша профессия</h2>
        <p>
            Новый, уютный салон «Красота от А до Я» приглашает Вас по адресу: г. Екатеринбург, ул.Библиотечная 45.
            У нас Вы получите не только высококачественные услуги, по реально-доступным ценам, с дружеской атмосферой и эстетическим удовольствием для глаз, но и отличное настроение!
        </p>
        <ul class="actions">
            <li><a href="#one" class="button scrolly">Узнать больше</a></li>
        </ul>
    </div>
</section>

Beauty Salon/Views/Shared/ContactsPartial.cshtml
@using Beauty_Salon.Service

<section id="three" class="wrapper style1 fade-up">
<div class="inner">
    <h2>Контакты</h2>
    <p>У вас есть вопросы? Мы с радостью ответим на каждый из них</p>
    <div class="split style1">
        <section>
            <form method="post" action="#">
                <div class="fields">
                    <div class="field half">
                        <label for="name">Ваше имя</label>
                        <input type="text" name="name" id="name" />
                    </div>
                    <div class="field half">
                        <label for="email">Email</label>
                        <input type="text" name="email" id="email" />
                    </div>
                    <div class="field">
                        <label for="message">Сообщение</label>
                        <textarea name="message" id="message" rows="5"></textarea>
                    </div>
                </div>
                <ul class="actions">
                    <li><a href="" class="button submit">Отправить</a></li>
                </ul>
            </form>
        </section>
        <section>
            <ul class="contact">
                <li>
                    <h3>Адрес</h3>
                    <span>г. Екатеринбург <br/>
                        ул. Библиотечная 45</span>
                </li>
                <li>
                    <h3>Телефон</h3>
                    <span>@Config.CompanyPhone</span>
                </li>
                <li>
                    <h3>Мы в социальных сетях</h3>
                    <ul class="icons">
                        <li><a href="@Config.CompanyInstagram" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
                    </ul>
                </li>
            </ul>
        </section>
    </div>
</div>
</section>

Beauty Salon/Views/Shared/CssPartial.cshtml
<noscript><link rel="stylesheet" href="~/css/main.css" /></noscript>
<link rel="stylesheet" href="~/css/main.css" asp-append-version="true" />

Beauty Salon/Views/Shared/FooterPartial.cshtml
<footer id="footer" class="wrapper style1-alt">
    <div class="inner">
        <ul class="menu">
            <li>&copy; Untitled. All rights reserved.</li>
            <li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
        </ul>
    </div>
</footer>

Beauty Salon/Views/Shared/HeaderPartial.cshtml
@using Beauty_Salon.Service
<header id="header">
    <a href="index.html" class="title">Hyperspace</a>
    <nav>
        <ul>
            <li><a href="index.html">Home</a></li>
            <li><a href="generic.html" class="active">Generic</a></li>
            <li><a href="elements.html">Elements</a></li>
        </ul>
    </nav>
</header>

Beauty Salon/Views/Shared/MastersPartial.cshtml
<section id="second" class="main special">
    <header class="major">
        <h2>Ipsum consequat</h2>
        <p>
            Donec imperdiet consequat consequat. Suspendisse feugiat congue<br />
            posuere. Nulla massa urna, fermentum eget quam aliquet.
        </p>
    </header>
    <ul class="statistics">
        <li class="style1">
            <span class="icon solid fa-code-branch"></span>
            <strong>5,120</strong> Etiam
        </li>
        <li class="style2">
            <span class="icon fa-folder-open"></span>
            <strong>8,192</strong> Magna
        </li>
        <li class="style3">
            <span class="icon solid fa-signal"></span>
            <strong>2,048</strong> Tempus
        </li>
        <li class="style4">
            <span class="icon solid fa-laptop"></span>
            <strong>4,096</strong> Aliquam
        </li>
        <li class="style5">
            <span class="icon fa-gem"></span>
            <strong>1,024</strong> Nullam
        </li>
    </ul>
    <p class="content">Nam elementum nisl et mi a commodo porttitor. Morbi sit amet nisl eu arcu faucibus hendrerit vel a risus. Nam a orci mi, elementum ac arcu sit amet, fermentum pellentesque et purus. Integer maximus varius lorem, sed convallis diam accumsan sed. Etiam porttitor placerat sapien, sed eleifend a enim pulvinar faucibus semper quis ut arcu. Ut non nisl a mollis est efficitur vestibulum. Integer eget purus nec nulla mattis et accumsan ut magna libero. Morbi auctor iaculis porttitor. Sed ut magna ac risus et hendrerit scelerisque. Praesent eleifend lacus in lectus aliquam porta. Cras eu ornare dui curabitur lacinia.</p>
    <footer class="major">
        <ul class="actions special">
            <li><a href="generic.html" class="button">Learn More</a></li>
        </ul>
    </footer>
</section>

Beauty Salon/Views/Shared/MetatagsPartial.cshtml
@using Beauty_Salon.Service

<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
@if (ViewBag.Title != null)
{
    <title>@ViewBag.Title</title>
}
else
{
    <title>@Config.CompanyName</title>
}
@if (ViewBag.Description != null)
{
    <meta name="description" content="@ViewBag.Description" />
}
@if (ViewBag.Keywords != null)
{
    <meta name="keywords" content="@ViewBag.Keywords" />
}

Beauty Salon/Views/Shared/ScriptsPartial.cshtml
<script src="~/js/jquery.min.js"></script>
<script src="~/js/jquery.scrollex.min.js"></script>
<script src="~/js/jquery.scrolly.min.js"></script>
<script src="~/js/browser.min.js"></script>
<script src="~/js/breakpoints.min.js"></script>
<script src="~/js/util.js"></script>
<script src="~/js/main.js"></script>
@*<scripts scr="~/js/scripts.min.js" asp-append-version="true"></scripts>*@

Beauty Salon/Views/Shared/ServicesPartial.cshtml
<section id="one" class="wrapper style2 spotlights">
    <section>
        <a href="#" class="image"><img src="images/ladycut.jpg" alt="" data-position="center center" /></a>
        <div class="content">
            <div class="inner">
                <h2>Женский зал</h2>
                <ul class="actions">
                    <li><a href="generic.html" class="button">Прайс</a></li>
                </ul>
            </div>
        </div>
    </section>
    <section>
        <a href="#" class="image"><img src="images/mancut.jpg" alt="" data-position="top center" /></a>
        <div class="content">
            <div class="inner">
                <h2>Мужской зал</h2>
                <ul class="actions">
                    <li><a href="generic.html" class="button">Прайс</a></li>
                </ul>
            </div>
        </div>
    </section>
    <section>
        <a href="#" class="image"><img src="images/manikur.jpg" alt="" data-position="25% 25%" /></a>
        <div class="content">
            <div class="inner">
                <h2>Маникюр</h2>
                <ul class="actions">
                    <li><a href="generic.html" class="button">Прайс</a></li>
                </ul>
            </div>
        </div>
    </section>
    <section>
        <a href="#" class="image"><img src="images/pedicur.jpg" alt="" data-position="25% 25%" /></a>
        <div class="content">
            <div class="inner">
                <h2>Педикюр</h2>
                <ul class="actions">
                    <li><a href="generic.html" class="button">Прайс</a></li>
                </ul>
            </div>
        </div>
    </section>
    <section>
        <a href="#" class="image"><img src="images/shugaring_woman.jpg" alt="" data-position="25% 25%" /></a>
        <div class="content">
            <div class="inner">
                <h2>Шугаринг женский</h2>
                <ul class="actions">
                    <li><a href="generic.html" class="button">Прайс</a></li>
                </ul>
            </div>
        </div>
    </section>
    <section>
        <a href="#" class="image"><img src="images/man_shugaring.jpg" alt="" data-position="25% 25%" /></a>
        <div class="content">
            <div class="inner">
                <h2>Шугаринг мужской</h2>
                <ul class="actions">
                    <li><a href="generic.html" class="button">Прайс</a></li>
                </ul>
            </div>
        </div>
    </section>
    <section>
        <a href="#" class="image"><img src="images/criosauna.jpg" alt="" data-position="25% 25%" /></a>
        <div class="content">
            <div class="inner">
                <h2>Криосауна</h2>
                <ul class="actions">
                    <li><a href="generic.html" class="button">Прайс</a></li>
                </ul>
            </div>
        </div>
    </section>
</section>

Beauty Salon/Views/Shared/SidebarPartial.cshtml
<section id="sidebar">
    <div class="inner">
        <nav>
            <ul>
                <li><a href="#intro">О салоне</a></li>
                <li><a href="#one">Наши услуги</a></li>
                <li><a href="#three">Контакты</a></li>
            </ul>
        </nav>
    </div>
</section>

Beauty Salon/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>

<html>
<head>
    @await Html.PartialAsync("MetatagsPartial")
    @await Html.PartialAsync("CssPartial")
</head>
<body>

    <!-- Sidebar -->
    @await Html.PartialAsync("SidebarPartial")

    <!-- Wrapper -->
    <div id="wrapper">
        @RenderBody()
        <!-- О салоне -->
        @await Html.PartialAsync("AboutPartial")
        <!-- Наши услуги -->
        @await Html.PartialAsync("ServicesPartial")
        <!-- Контакты -->
        @await Html.PartialAsync("ContactsPartial")
    </div>

    <!-- Footer -->
@await Html.PartialAsync("FooterPartial")
@await Html.PartialAsync("ScriptsPartial")

</body>
</html>